version: "3"
services:
  php8-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php8-container
    volumes:
      - ./app:/var/www/project 
    ports: 
      - 9000:9000

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8-service

  node-service:
          image: node:latest
          container_name: node-container
          command: ["sh", "-c", "npm install && npm encore dev --watch"]
          volumes: 
              - ./app:/var/www/project
          working_dir: /var/www/project

